language: ruby
rvm:
  - 2.0.0
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
  - bundle update
  - mysql -e 'create database myapp_test'
  - psql -c 'create database myapp_test' -U postgres
