language: ruby
rvm:
  - 2.0.0
env:
  - DB=mysql
script:
  - RAILS_ENV=development bundle exec rake --trace db:migrate test
before_script:
  - RAILS_ENV=development bundle exec bundle update
  - RAILS_ENV=development bundle exec rake twitter:stream
